# version: "3.9"
services:
  frontend:
    build: .
    ports:
      - "5002:80"
    volumes:
      - tooling_frontend:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: toolingdb
      MYSQL_USER: chidi
      MYSQL_PASSWORD: Admin123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
      - ./html/tooling_db_schema.sql:/docker-entrypoint-initdb.d/tooling_db_schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  tooling_frontend:
  db:
